import {requireUser} from '@/lib/auth'
import Link from 'next/link'
import {getStudentAnnouncements} from '@/lib/cached-data'
import {displayLabel} from '@/lib/labels'
export default async function Page() {
 const {supabase,user,profile}=await requireUser('student')
 const [{data:announcements,error},{data:registrations}]=await Promise.all([
  getStudentAnnouncements(profile.batch),
  supabase.from('registrations').select('registration_id,status,remarks,verified_at,submitted_at').eq('student_id',user.id).order('submitted_at',{ascending:false})
 ])
 const counts={pending:registrations?.filter(r=>r.status==='pending').length||0,ongoing:registrations?.filter(r=>r.status==='ongoing').length||0,completed:registrations?.filter(r=>r.status==='completed').length||0,total:registrations?.length||0}
 const updates=(registrations||[]).filter(r=>r.status!=='pending').slice(0,3)
 return <div className="space-y-7">
  <section className="flex justify-between items-start gap-5"><div><p className="eyebrow">{profile.batch} · STUDENT DASHBOARD</p><h1 className="dashboardGreeting !mb-2">Hello, {profile.first_name}.</h1><p className="muted text-sm">Here is a clear view of your make-up duty progress.</p></div><Link href="/student/registration" className="primary text-sm whitespace-nowrap">＋ New registration</Link></section>
  {!!updates.length&&<section className="dashboardCard p-5" aria-labelledby="recent-updates"><div className="flex justify-between gap-4 items-center"><div><p className="eyebrow !mb-2">NOTIFICATIONS</p><h2 id="recent-updates" className="font-semibold">Recent registration updates</h2></div><Link href="/student/notifications" className="text-sm underline">View all</Link></div><div className="space-y-2 mt-4">{updates.map(update=><p className={update.status==='denied'?'notice !mb-0':'update-row'} key={update.registration_id}><strong>{displayLabel(update.status)}</strong>{update.remarks&&<span> · {update.remarks}</span>}</p>)}</div></section>}
  <section className="themePanel p-7 md:p-8 flex flex-col md:flex-row justify-between gap-8 overflow-hidden relative"><div className="relative z-10"><p className="text-xs opacity-75 uppercase tracking-widest">Your progress</p><h2 className="text-2xl font-semibold mt-3">Keep every duty on track.</h2><p className="text-sm opacity-80 mt-2 max-w-lg">Review requests, check approved schedules, and follow announcements from your Clinical Head.</p></div><div className="flex gap-8 relative z-10"><div><strong className="text-3xl">{counts.completed}</strong><small className="block opacity-75 mt-1">Completed</small></div><div><strong className="text-3xl">{counts.total}</strong><small className="block opacity-75 mt-1">Total requests</small></div></div><span className="absolute -right-12 -bottom-24 w-64 h-64 rounded-full border border-white/20"/></section>
  <section className="grid grid-cols-2 lg:grid-cols-4 gap-4">{Object.entries(counts).map(([label,value],index)=><article key={label} className="dashboardCard p-5" data-searchable><div className="flex justify-between items-center"><span className="countIcon">{['◷','↻','✓','∑'][index]}</span><span className="badge">{displayLabel(label)}</span></div><p className="themeValue text-3xl font-semibold mt-5">{value}</p><p className="muted text-xs mt-1">{displayLabel(label)} registrations</p></article>)}</section>
  <section className="grid lg:grid-cols-[1.7fr_1fr] gap-5"><div><div className="flex justify-between items-center mb-4"><h2 className="text-lg font-semibold">Latest announcements</h2><span className="muted text-xs">From your Clinical Head</span></div>{error&&<p className="notice" role="alert">Unable to load announcements. Check the database setup.</p>}<div className="space-y-3">{announcements?.slice(0,4).map(a=><article key={a.announcement_id} className="dashboardCard p-5" data-searchable><div className="flex justify-between gap-3 mb-3"><span className="badge">{a.batch||'General'}</span><time className="muted text-xs">{new Date(a.posted_at).toLocaleDateString('en-PH',{timeZone:'Asia/Manila'})}</time></div><h3 className="font-semibold">{a.title}</h3><p className="text-sm text-slate-600 whitespace-pre-wrap mt-2 leading-6">{a.content}</p></article>)}</div>{!announcements?.length&&!error&&<div className="dashboardCard p-8 text-center muted">No announcements yet.</div>}</div><aside><h2 className="text-lg font-semibold mb-4">Quick actions</h2><div className="dashboardCard p-3 space-y-2"><Link className="block p-4 rounded-xl hover:bg-slate-50" href="/student/registration"><strong className="block text-sm">Register a duty →</strong><span className="muted text-xs">Choose a date and submit proof</span></Link><Link className="block p-4 rounded-xl hover:bg-slate-50" href="/student/schedule"><strong className="block text-sm">View my schedule →</strong><span className="muted text-xs">See approved and ongoing duties</span></Link><Link className="block p-4 rounded-xl hover:bg-slate-50" href="/student/profile"><strong className="block text-sm">Open my profile →</strong><span className="muted text-xs">Review tallies and contact details</span></Link></div></aside></section>
 </div>
}

