'use client'
import {useState} from 'react'
import styles from './DutyCalendar.module.css'

type Schedule={schedule_id:number;date:string;time_slot:string;max_capacity:number;current_count:number;status:string;batch?:string|null;clinical_area:string}
function CalendarIcon({kind}:{kind:'open'|'registered'|'closed'}){return <svg viewBox="0 0 24 24" aria-hidden="true">{kind==='open'?<><circle cx="12" cy="12" r="9"/><path d="m9 12 2 2 4-4"/></>:kind==='registered'?<><path d="M5 3h14v18H5z"/><path d="m8 12 2 2 5-5"/></>:<><circle cx="12" cy="12" r="9"/><path d="M8 12h8"/></>}</svg>}

export default function AdminScheduleCalendar({schedules}:{schedules:Schedule[]}){
 const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Manila'}),initial=schedules.find(schedule=>schedule.date>=today)?.date.slice(0,7)||schedules.at(-1)?.date.slice(0,7)||today.slice(0,7)
 const [month,setMonth]=useState(initial),[year,monthNumber]=month.split('-').map(Number)
 const firstWeekday=new Date(year,monthNumber-1,1).getDay(),days=new Date(year,monthNumber,0).getDate(),monthRows=schedules.filter(schedule=>schedule.date.startsWith(month))
 const monthLabel=new Intl.DateTimeFormat('en-PH',{month:'long',year:'numeric'}).format(new Date(year,monthNumber-1,1))
 function move(change:number){const next=new Date(year,monthNumber-1+change,1);setMonth(`${next.getFullYear()}-${String(next.getMonth()+1).padStart(2,'0')}`)}
 return <section className={styles.section} aria-labelledby="admin-calendar-title"><div className={styles.header}><div><p className={styles.kicker}>MANAGE DUTY DATES</p><h2 id="admin-calendar-title">Schedule calendar</h2><p>Created schedules appear here immediately. Select a schedule to open its editing controls below.</p></div><div className={styles.controls}><button className="adminIconButton" type="button" onClick={()=>move(-1)} aria-label="Previous month">‹</button><label><span>Month</span><input type="month" value={month} onChange={event=>event.target.value&&setMonth(event.target.value)} aria-label="Calendar month"/></label><button className="adminIconButton" type="button" onClick={()=>move(1)} aria-label="Next month">›</button></div></div>
  <div className={styles.monthSummary}><strong>{monthLabel}</strong><span className={styles.availableCount}><CalendarIcon kind="open"/>{monthRows.filter(row=>row.status==='open').length} Open</span><span><CalendarIcon kind="registered"/>{monthRows.reduce((sum,row)=>sum+row.current_count,0)} Registrations</span><span><CalendarIcon kind="closed"/>{monthRows.filter(row=>row.status==='closed').length} Closed</span></div>
  <div className={styles.legend}><span className={styles.availableLegend}><CalendarIcon kind="open"/>Open schedule</span><span className={styles.registeredLegend}><CalendarIcon kind="registered"/>Has Registrations</span><span className={styles.fullLegend}><CalendarIcon kind="closed"/>Closed or full</span></div><p className={styles.mobileHint}>Swipe sideways to view every day of the month.</p>
  <div className={styles.calendarViewport} tabIndex={0} aria-label={`${monthLabel} schedule calendar, horizontally scrollable on small screens`}><div className={styles.calendar}>{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day,index)=><div className={`${styles.weekday} ${(index===0||index===6)?styles.weekend:''}`} key={day}>{day}</div>)}{Array.from({length:firstWeekday},(_,index)=><div className={styles.blank} key={`blank-${index}`} aria-hidden="true"/>)}{Array.from({length:days},(_,index)=>{const date=`${month}-${String(index+1).padStart(2,'0')}`,entries=monthRows.filter(schedule=>schedule.date===date);return <article className={`${styles.day} ${date===today?styles.today:''} ${entries.length?styles.available:styles.unavailable}`} key={date}><div className={styles.dayHead}><time dateTime={date}>{index+1}</time>{date===today&&<span>Today</span>}</div><div className={styles.slots}>{entries.map(schedule=>{const closed=schedule.status==='closed'||schedule.current_count>=schedule.max_capacity,hasRegistrations=schedule.current_count>0;return <a href={`#schedule-${schedule.schedule_id}`} className={closed?styles.full:hasRegistrations?styles.registered:styles.slotLink} key={schedule.schedule_id}><CalendarIcon kind={closed?'closed':hasRegistrations?'registered':'open'}/><span><strong>{schedule.time_slot} · {closed?'Closed':hasRegistrations?'In use':'Open'}</strong><small>{schedule.batch||'All batches'} · {schedule.current_count}/{schedule.max_capacity}</small></span><b aria-hidden="true">↓</b></a>})}{!entries.length&&<span className={styles.noSchedule}><CalendarIcon kind="closed"/>Not scheduled</span>}</div></article>})}</div></div>
 </section>
}

