'use client'
import {useRef} from 'react'
import ConfirmButton from '@/components/ConfirmButton'
import {setStudentAccess,updateStudentAccount} from '@/app/admin/students/actions'
import {displayName} from '@/lib/names'

type Props={student:{user_id:string;student_number:string|null;first_name:string;middle_initial:string|null;last_name:string;batch:string|null;year_level:string|null;year_section:string|null;is_active:boolean|null}}

export default function StudentAccountManager({student}:Props){
 const dialog=useRef<HTMLDialogElement>(null)
 return <><button type="button" className="adminSecondary student-manage-trigger" onClick={()=>dialog.current?.showModal()}>Manage</button><dialog ref={dialog} className="student-manager" onClick={event=>{if(event.target===event.currentTarget)dialog.current?.close()}}><div className="student-manager-panel"><div className="student-manager-head"><div><p className="eyebrow">USER MANAGEMENT</p><h2>{displayName(student)}</h2><p>{student.student_number} · {student.batch} · {student.year_section||student.year_level+' year'}</p></div><button type="button" aria-label="Close student management" onClick={()=>dialog.current?.close()}>×</button></div><div className="student-manager-status"><span className={`status-chip ${student.is_active===false?'is-archived':'is-active'}`}>{student.is_active===false?'Suspended':'Active'}</span><span>Student account</span></div><form action={updateStudentAccount} className="student-manager-section"><input type="hidden" name="user_id" value={student.user_id}/><h3>Academic Record</h3><p>Students manage their own name, contact details, and password from My Profile.</p><div className="admin-form-grid"><label>Year Level<input value={student.year_level||''} readOnly aria-readonly="true"/></label><label>Year &amp; Section<input name="year_section" defaultValue={student.year_section||''} placeholder={`${student.year_level?.[0]||'4'}NU-05`} pattern={`${student.year_level?.[0]||'[234]'}NU-[0-9]{2}`} maxLength={6} autoCapitalize="characters" required/></label><input type="hidden" name="first_name" value={student.first_name}/><input type="hidden" name="middle_initial" value={student.middle_initial||''}/><input type="hidden" name="last_name" value={student.last_name}/></div><ConfirmButton className="primary" message="Save this academic record change?">Save Academic Record</ConfirmButton></form><form action={setStudentAccess} className="student-manager-section student-access-row"><input type="hidden" name="user_id" value={student.user_id}/><input type="hidden" name="active" value={String(student.is_active===false)}/><div><h3>{student.is_active===false?'Restore Access':'Suspend Access'}</h3><p>{student.is_active===false?'Allow this student to sign in again.':'Immediately block this student from signing in.'}</p></div><ConfirmButton className={student.is_active===false?'primary':'dangerButton'} message={`${student.is_active===false?'Restore':'Suspend'} access for ${student.student_number}?`}>{student.is_active===false?'Restore Access':'Suspend Access'}</ConfirmButton></form></div></dialog></>
}
