-- Fresh databases only. Creates the six core application tables.
-- A production project also needs the baseline columns, RLS policies, storage
-- bucket, helper functions and triggers described in EXISTING_DATABASE.md.
-- Identity columns replace the context schema sequence defaults.

CREATE TABLE public.users (
  user_id uuid NOT NULL,
  student_number character varying UNIQUE,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['student'::character varying, 'clinical_head'::character varying]::text[])),
  first_name character varying NOT NULL,
  middle_initial character varying(1) CHECK (middle_initial IS NULL OR middle_initial::text ~ '^[A-Z]$'),
  last_name character varying NOT NULL,
  year_level character varying CHECK (year_level::text = ANY (ARRAY['2nd'::character varying, '3rd'::character varying, '4th'::character varying]::text[])),
  year_section character varying(6) CHECK (year_section IS NULL OR year_section::text ~ '^[234]NU-[0-9]{2}$'),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT users_pkey PRIMARY KEY (user_id),
  CONSTRAINT users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.student_profiles (
  profile_id integer GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL UNIQUE,
  photo_url character varying,
  course_block character varying,
  contact_number character varying,
  address text,
  guardian_name character varying,
  guardian_contact character varying,
  clinical_area character varying,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT student_profiles_pkey PRIMARY KEY (profile_id),
  CONSTRAINT student_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.announcements (
  announcement_id integer GENERATED BY DEFAULT AS IDENTITY,
  posted_by uuid NOT NULL,
  title character varying NOT NULL,
  content text NOT NULL,
  posted_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  CONSTRAINT announcements_pkey PRIMARY KEY (announcement_id),
  CONSTRAINT announcements_posted_by_fkey FOREIGN KEY (posted_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.mud_schedules (
  schedule_id integer GENERATED BY DEFAULT AS IDENTITY,
  date date NOT NULL,
  time_slot character varying NOT NULL CHECK (time_slot::text = ANY (ARRAY['AM'::character varying, 'PM'::character varying]::text[])),
  max_capacity integer NOT NULL CHECK (max_capacity > 0),
  current_count integer NOT NULL DEFAULT 0 CHECK (current_count >= 0),
  year_level character varying CHECK (year_level::text = ANY (ARRAY['2nd'::character varying, '3rd'::character varying, '4th'::character varying, 'all'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'open'::character varying CHECK (status::text = ANY (ARRAY['open'::character varying, 'closed'::character varying]::text[])),
  created_by uuid NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT mud_schedules_pkey PRIMARY KEY (schedule_id),
  CONSTRAINT mud_schedules_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.registrations (
  registration_id integer GENERATED BY DEFAULT AS IDENTITY,
  student_id uuid NOT NULL,
  schedule_id integer NOT NULL,
  duty_type character varying NOT NULL CHECK (duty_type::text = ANY (ARRAY['excused'::character varying, 'unexcused'::character varying, 'waived'::character varying]::text[])),
  receipt_url character varying,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'verified'::character varying, 'denied'::character varying, 'ongoing'::character varying, 'completed'::character varying]::text[])),
  recommendation character varying CHECK (recommendation::text = ANY (ARRAY['excused'::character varying, 'waived'::character varying, 'unexcused'::character varying]::text[])),
  submitted_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  verified_at timestamp without time zone,
  verified_by uuid,
  remarks text,
  CONSTRAINT registrations_pkey PRIMARY KEY (registration_id),
  CONSTRAINT registrations_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.users(user_id),
  CONSTRAINT registrations_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.mud_schedules(schedule_id),
  CONSTRAINT registrations_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.verification_notes (
  note_id integer GENERATED BY DEFAULT AS IDENTITY,
  registration_id integer NOT NULL,
  note_text text NOT NULL,
  created_by uuid NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT verification_notes_pkey PRIMARY KEY (note_id),
  CONSTRAINT verification_notes_registration_id_fkey FOREIGN KEY (registration_id) REFERENCES public.registrations(registration_id),
  CONSTRAINT verification_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id)
);

