-- Run once in Supabase SQL Editor after 002_performance_concurrency.sql.
-- Adds cohort identity rules, password-reset requests and an atomic manual tally.

ALTER TABLE public.student_profiles
 ADD COLUMN IF NOT EXISTS manual_tally_count integer NOT NULL DEFAULT 0;

DO $$ BEGIN
 ALTER TABLE public.student_profiles ADD CONSTRAINT mud_manual_tally_range
  CHECK (manual_tally_count BETWEEN 0 AND 10000);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- NOT VALID keeps older imported accounts readable while enforcing the rule for
-- every newly created or edited student. Correct older demo accounts with the
-- updated prepare-sql-seed script, then validate this constraint when ready.
DO $$ BEGIN
 ALTER TABLE public.users ADD CONSTRAINT mud_student_cohort_identity CHECK (
  role <> 'student' OR
  (batch='Sanghaya' AND student_number LIKE '2025-%' AND year_level='2nd') OR
  (batch='Solaris' AND student_number LIKE '2024-%' AND year_level='3rd') OR
  (batch='Astraea' AND student_number LIKE '2023-%' AND year_level='4th')
 ) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.password_reset_requests (
 request_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id uuid NOT NULL UNIQUE REFERENCES public.users(user_id) ON DELETE CASCADE,
 identifier text NOT NULL,
 category text NOT NULL CHECK (category IN ('Sanghaya','Solaris','Astraea','Admin')),
 status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','resolved')),
 requested_at timestamptz NOT NULL DEFAULT now(),
 resolved_at timestamptz,
 resolved_by uuid REFERENCES public.users(user_id)
);

CREATE INDEX IF NOT EXISTS mud_password_reset_status_requested
 ON public.password_reset_requests(status,requested_at DESC);

ALTER TABLE public.password_reset_requests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS password_reset_admin_read ON public.password_reset_requests;
DROP POLICY IF EXISTS password_reset_admin_update ON public.password_reset_requests;
CREATE POLICY password_reset_admin_read ON public.password_reset_requests
 FOR SELECT TO authenticated USING(public.is_clinical_head());
CREATE POLICY password_reset_admin_update ON public.password_reset_requests
 FOR UPDATE TO authenticated USING(public.is_clinical_head())
 WITH CHECK(public.is_clinical_head());

CREATE OR REPLACE FUNCTION public.adjust_student_tally(target_user uuid,amount_to_add integer)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE updated_total integer;
BEGIN
 IF NOT public.is_clinical_head() THEN RAISE EXCEPTION 'Clinical Head access required'; END IF;
 IF amount_to_add IS NULL OR amount_to_add < 1 OR amount_to_add > 30 THEN
  RAISE EXCEPTION 'Tally adjustment must be from 1 to 30';
 END IF;
 IF NOT EXISTS(SELECT 1 FROM public.users WHERE user_id=target_user AND role='student') THEN
  RAISE EXCEPTION 'Student account not found';
 END IF;
 INSERT INTO public.student_profiles(user_id,manual_tally_count)
 VALUES(target_user,amount_to_add)
 ON CONFLICT(user_id) DO UPDATE SET
  manual_tally_count=public.student_profiles.manual_tally_count+EXCLUDED.manual_tally_count,
  updated_at=now()
 RETURNING manual_tally_count INTO updated_total;
 RETURN updated_total;
END $$;

REVOKE ALL ON FUNCTION public.adjust_student_tally(uuid,integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.adjust_student_tally(uuid,integer) TO authenticated;

ANALYZE public.student_profiles;
ANALYZE public.password_reset_requests;
