-- Run after 003_product_adjustments.sql.
-- Records the source and automatic ratio behind every Clinical Head tally change.

CREATE TABLE IF NOT EXISTS public.tally_adjustments (
 adjustment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 student_id uuid NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
 added_by uuid NOT NULL REFERENCES public.users(user_id),
 duty_type text NOT NULL CHECK (duty_type IN ('excused','unexcused','waived')),
 missed_count integer NOT NULL CHECK (missed_count BETWEEN 1 AND 180),
 duty_ratio integer NOT NULL CHECK (duty_ratio IN (1,3,6)),
 duty_total integer GENERATED ALWAYS AS (missed_count*duty_ratio) STORED,
 created_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT mud_tally_ratio_by_type CHECK (
  (duty_type IN ('excused','waived') AND duty_ratio=1) OR
  (duty_type='unexcused' AND duty_ratio IN (3,6))
 )
);

CREATE INDEX IF NOT EXISTS mud_tally_adjustments_student_created
 ON public.tally_adjustments(student_id,created_at DESC);

ALTER TABLE public.tally_adjustments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tally_adjustments_read ON public.tally_adjustments;
CREATE POLICY tally_adjustments_read ON public.tally_adjustments
 FOR SELECT TO authenticated
 USING(student_id=auth.uid() OR public.is_clinical_head());

CREATE OR REPLACE FUNCTION public.apply_tally_adjustment(
 target_user uuid, missed_count integer, duty_category text, duty_ratio integer
) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE calculated integer; updated_total integer;
BEGIN
 IF NOT public.is_clinical_head() THEN RAISE EXCEPTION 'Clinical Head access required'; END IF;
 IF NOT EXISTS(SELECT 1 FROM public.users WHERE user_id=target_user AND role='student') THEN RAISE EXCEPTION 'Student account not found'; END IF;
 IF missed_count IS NULL OR missed_count<1 OR missed_count>180 THEN RAISE EXCEPTION 'Missed duty count must be from 1 to 180'; END IF;
 IF (duty_category IN ('excused','waived') AND duty_ratio<>1)
    OR (duty_category='unexcused' AND duty_ratio NOT IN (3,6))
    OR duty_category NOT IN ('excused','unexcused','waived') THEN
  RAISE EXCEPTION 'Invalid duty tally ratio';
 END IF;
 calculated:=missed_count*duty_ratio;
 IF calculated>180 THEN RAISE EXCEPTION 'One adjustment cannot exceed 180 duties'; END IF;

 INSERT INTO public.tally_adjustments(student_id,added_by,duty_type,missed_count,duty_ratio)
 VALUES(target_user,auth.uid(),duty_category,missed_count,duty_ratio);
 INSERT INTO public.student_profiles(user_id,manual_tally_count)
 VALUES(target_user,calculated)
 ON CONFLICT(user_id) DO UPDATE SET
  manual_tally_count=public.student_profiles.manual_tally_count+EXCLUDED.manual_tally_count,
  updated_at=now()
 RETURNING manual_tally_count INTO updated_total;
 RETURN updated_total;
END $$;

REVOKE ALL ON FUNCTION public.apply_tally_adjustment(uuid,integer,text,integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.apply_tally_adjustment(uuid,integer,text,integer) TO authenticated;
ANALYZE public.tally_adjustments;
