-- Dynamic batch catalog and account access controls.
-- Run after 004_automatic_tally_ratios.sql in the Supabase SQL Editor.

BEGIN;

CREATE TABLE IF NOT EXISTS public.batches (
 batch_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name varchar(40) NOT NULL UNIQUE CHECK (name ~ '^[A-Za-z][A-Za-z -]{1,39}$'),
 student_year_prefix varchar(4) NOT NULL UNIQUE CHECK (student_year_prefix ~ '^[0-9]{4}$'),
 year_level varchar(3) NOT NULL CHECK (year_level IN ('2nd','3rd','4th')),
 theme_color varchar(7) NOT NULL CHECK (theme_color ~ '^#[0-9A-Fa-f]{6}$'),
 logo_path text NOT NULL DEFAULT '/logos/mudernize-logo.png',
 is_active boolean NOT NULL DEFAULT true,
 created_by uuid REFERENCES public.users(user_id),
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.batches(name,student_year_prefix,year_level,theme_color,logo_path)
VALUES
 ('Sanghaya','2025','2nd','#ffacec','/logos/sanghaya.png'),
 ('Astraea','2023','4th','#401268','/logos/astraea.png'),
 ('Solaris','2024','3rd','#7a0000','/logos/solaris.png')
ON CONFLICT(name) DO UPDATE SET
 student_year_prefix=EXCLUDED.student_year_prefix,
 year_level=EXCLUDED.year_level,
 theme_color=EXCLUDED.theme_color,
 logo_path=EXCLUDED.logo_path;

ALTER TABLE public.users ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS middle_initial varchar(1);

ALTER TABLE public.users DROP CONSTRAINT IF EXISTS mud_student_cohort_identity;
ALTER TABLE public.password_reset_requests DROP CONSTRAINT IF EXISTS password_reset_requests_category_check;

DO $$ BEGIN
 ALTER TABLE public.users ADD CONSTRAINT mud_users_batch_catalog
  FOREIGN KEY(batch) REFERENCES public.batches(name) ON UPDATE CASCADE ON DELETE RESTRICT NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
 ALTER TABLE public.mud_schedules ADD CONSTRAINT mud_schedules_batch_catalog
  FOREIGN KEY(batch) REFERENCES public.batches(name) ON UPDATE CASCADE ON DELETE RESTRICT NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
 ALTER TABLE public.announcements ADD CONSTRAINT mud_announcements_batch_catalog
  FOREIGN KEY(batch) REFERENCES public.batches(name) ON UPDATE CASCADE ON DELETE RESTRICT NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE OR REPLACE FUNCTION public.validate_student_batch()
RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$
DECLARE rule public.batches%ROWTYPE;
BEGIN
 IF NEW.role<>'student' THEN RETURN NEW; END IF;
 SELECT * INTO rule FROM public.batches WHERE name=NEW.batch AND is_active;
 IF NOT FOUND OR NEW.student_number NOT LIKE rule.student_year_prefix || '-%' OR NEW.year_level<>rule.year_level THEN
  RAISE EXCEPTION 'Student ID, batch, and year do not match an active batch';
 END IF;
 RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS mud_validate_student_batch ON public.users;
CREATE TRIGGER mud_validate_student_batch BEFORE INSERT OR UPDATE OF student_number,batch,year_level,role
ON public.users FOR EACH ROW EXECUTE FUNCTION public.validate_student_batch();

ALTER TABLE public.batches ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS batches_read ON public.batches;
CREATE POLICY batches_read ON public.batches FOR SELECT TO anon,authenticated
USING(is_active OR (auth.role()='authenticated' AND public.is_clinical_head()));

CREATE INDEX IF NOT EXISTS mud_batches_active_name ON public.batches(is_active,name);
CREATE INDEX IF NOT EXISTS mud_users_active_role ON public.users(is_active,role);

CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE m jsonb; rule public.batches%ROWTYPE; middle text;
BEGIN
 SELECT raw_app_meta_data INTO m FROM auth.users WHERE id=NEW.id;
 IF NOT FOUND THEN RETURN NEW; END IF;
 IF m->>'role' IS NULL OR m->>'role' NOT IN ('student','clinical_head') THEN RAISE EXCEPTION 'Accounts must be provisioned by a Clinical Head'; END IF;
 IF nullif(trim(m->>'first_name'),'') IS NULL OR nullif(trim(m->>'last_name'),'') IS NULL THEN RAISE EXCEPTION 'Names required'; END IF;
 middle=nullif(upper(trim(trailing '.' FROM trim(coalesce(m->>'middle_initial','')))), '');
 IF middle IS NOT NULL AND middle !~ '^[A-Z]$' THEN RAISE EXCEPTION 'Middle initial must be one letter'; END IF;
 IF m->>'role'='student' THEN
  SELECT * INTO rule FROM public.batches WHERE name=m->>'batch' AND is_active;
  IF NOT FOUND OR coalesce(m->>'student_number','') !~ '^[0-9]{4}-[0-9]{6}$'
     OR m->>'student_number' NOT LIKE rule.student_year_prefix || '-%'
     OR m->>'year_level'<>rule.year_level THEN RAISE EXCEPTION 'Student ID, batch and year required'; END IF;
 END IF;
 IF m->>'role'='clinical_head' AND coalesce(m->>'admin_number','') !~ '^[a-zA-Z0-9-]{3,40}$' THEN RAISE EXCEPTION 'Admin ID required'; END IF;
 INSERT INTO public.users(user_id,student_number,admin_number,role,first_name,middle_initial,last_name,year_level,batch,recommendation,is_active)
 VALUES(NEW.id,m->>'student_number',m->>'admin_number',m->>'role',m->>'first_name',middle,m->>'last_name',m->>'year_level',m->>'batch',m->>'recommendation',true);
 IF m->>'role'='student' THEN INSERT INTO public.student_profiles(user_id) VALUES(NEW.id); END IF;
 RETURN NEW;
END $$;

ANALYZE public.batches;
ANALYZE public.users;
COMMIT;
