import {requireUser} from '@/lib/auth'
import {getBatchConfigs} from '@/lib/batch-data'
import ConfirmButton from '@/components/ConfirmButton'
import ResetAfterSubmitForm from '@/components/ResetAfterSubmitForm'
import {removeBatch,saveBatch,setBatchStatus,updateBatchLogo} from './actions'

export default async function Page({searchParams:searchParamsPromise}:{searchParams:Promise<{error?:string;message?:string}>}){
 const searchParams=await searchParamsPromise
 await requireUser('clinical_head')
 const {data:batches,error,usingFallback}=await getBatchConfigs(true)
 return <div className="space-y-6 page-stack">
  <div className="page-heading"><p className="eyebrow">CLINICAL HEAD WORKSPACE</p><h1>Batch Management</h1><p className="muted text-sm">Create cohorts, control new sign-ins, and safely retire batches.</p></div>
  {searchParams.error&&<p className="notice" role="alert">{searchParams.error}</p>}{searchParams.message&&<p className="notice success-notice" role="status">{searchParams.message}</p>}
  {usingFallback&&<p className="notice" role="alert">Batch management requires database/005_batch_and_user_management.sql. Default batches are shown as a preview. {error?.message}</p>}
  <ResetAfterSubmitForm action={saveBatch} className="dashboardCard p-6 space-y-4"><div><h2 className="font-semibold text-lg">Create a Batch</h2><p className="muted text-xs mt-1">The student year prefix controls which IDs can be assigned to this cohort.</p></div><div className="batch-create-grid"><label>Batch Name<input name="name" required minLength={2} maxLength={40} placeholder="e.g. Hiraya"/></label><label>Student ID Year<input name="student_year_prefix" required inputMode="numeric" pattern="[0-9]{4}" placeholder="2026"/></label><label>Year Level<select name="year_level" defaultValue="2nd"><option>2nd</option><option>3rd</option><option>4th</option></select></label><label>Theme Color<input name="theme_color" type="color" defaultValue="#054191" required/></label><label className="batch-logo-field">Batch Logo <span className="muted">(Optional)</span><input name="logo" type="file" accept="image/png,image/jpeg,image/webp"/><small>Transparent PNG, JPG, or WebP · maximum 2 MB</small></label></div><ConfirmButton className="primary" message="Create this batch?">Create Batch</ConfirmButton></ResetAfterSubmitForm>
  <section><div className="section-heading"><div><h2 className="font-semibold text-lg">Available Batches</h2><p className="muted text-xs">Upload branding, archive cohorts with historical records, or delete unused batches.</p></div><span className="badge">{batches.filter(batch=>batch.is_active).length} Active</span></div><div className="batch-management-grid">{batches.map(batch=><article className="dashboardCard batch-management-card p-5" key={batch.name} data-searchable><div className="batch-card-head"><span className="batch-logo-preview"><img src={batch.logo_path} alt={`${batch.name} logo`}/></span><div><h3>{batch.name}</h3><p className="muted text-xs">{batch.student_year_prefix} IDs · {batch.year_level} year</p></div><span className={`status-chip ${batch.is_active?'is-active':'is-archived'}`}>{batch.is_active?'Active':'Archived'}</span></div><form action={updateBatchLogo} className="batch-logo-upload"><input type="hidden" name="name" value={batch.name}/><label>Replace Logo<input name="logo" type="file" accept="image/png,image/jpeg,image/webp" required/></label><ConfirmButton className="adminSecondary" message={`Replace the ${batch.name} logo?`}>Upload Logo</ConfirmButton></form><div className="batch-card-actions"><form action={setBatchStatus}><input type="hidden" name="name" value={batch.name}/><input type="hidden" name="active" value={String(!batch.is_active)}/><ConfirmButton className="adminSecondary" message={`${batch.is_active?'Archive':'Activate'} ${batch.name}?`}>{batch.is_active?'Archive':'Activate'}</ConfirmButton></form><form action={removeBatch}><input type="hidden" name="name" value={batch.name}/><ConfirmButton className="dangerButton" message={`Permanently delete ${batch.name}? Only unused batches can be deleted.`}>Delete</ConfirmButton></form></div></article>)}</div></section>
 </div>
}
